services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: snsapp
      POSTGRES_USER: snsapp
      POSTGRES_PASSWORD: snsapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
